{
 "title": "APC SmartUPS Dashboard (13365)",
 "description": "Dashboard to display metrics relating to APC Smart-UPS devices",
 "tags": [
  "telegraf",
  "snmp",
  "influxdb"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "dataSource", "query": "influxdb" },
   {
    "name": "host",
    "label": "Host",
    "query": "SHOW TAG VALUES FROM \"snmp.UPS\" WITH KEY = \"agent_host\""
   }
  ]
 },
 "panels": [
  {
   "title": "$host",
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "sysName" ], "type": "tag" }
     ],
     "measurement": "snmp.UPS",
     "select": [
      [
       { "params": [ "upsBasicIdentModel" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Model" ], "type": "alias" }
      ],
      [
       { "params": [ "upsBasicIdentName" ], "type": "field" },
       { "params": [ "Name" ], "type": "alias" }
      ],
      [
       { "params": [ "upsAdvIdentFirmwareRevision" ], "type": "field" },
       { "params": [ "Firmware" ], "type": "alias" }
      ],
      [
       { "params": [ "upsAdvIdentDateOfManufacture" ], "type": "field" },
       { "params": [ "Manufacture Date" ], "type": "alias" }
      ],
      [
       { "params": [ "upsAdvIdentSerialNumber" ], "type": "field" },
       { "params": [ "Serial" ], "type": "alias" }
      ],
      [
       { "params": [ "upsAdvIdentSkuNumber" ], "type": "field" },
       { "params": [ "SKU" ], "type": "alias" }
      ],
      [
       { "params": [ "upsBasicBatteryLastReplaceDate" ], "type": "field" },
       { "params": [ "Battery Replace Date" ], "type": "alias" }
      ],
      [
       { "params": [ "upsAdvBatteryInternalSKU" ], "type": "field" },
       { "params": [ "Internal Battery SKU" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 3 },
   "options": {
    "content": "<p style=\"text-align:center; vertical-align: middle;\">\r\n<img src=\"https://github.com/Condoamanti/grafana/blob/master/dashboard/apc-smartups/Logo.png?raw=true\" style=\"background-color:white\" height=\"125\" alt=\"APC\"/>\r\n</p>"
   }
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "The time seconds since the network management portion of the system was last re-initialized.",
   "gridPos": { "h": 4, "w": 4, "x": 2, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "snmp.UPS",
     "query": "SELECT \"sysUpTime\"  / 100 FROM \"snmp.UPS\" WHERE (\"agent_host\" =~ /^$host$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "sysUpTime" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "gauge",
   "description": "The current internal UPS temperature expressed in\nCelsius.",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_agent_host (fahrenheit)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "agent_host" ], "type": "tag" },
      { "params": [ "agent_host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "snmp.UPS",
     "query": "SELECT mean(\"upsAdvBatteryTemperature\") * 9/5 + 32 FROM \"snmp.UPS\" WHERE $timeFilter GROUP BY time($__interval), \"agent_host\", \"agent_host\" fill(none)",
     "select": [
      [
       { "params": [ "upsAdvBatteryTemperature" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "* 9/5 + 32" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "UPS Load",
   "type": "gauge",
   "description": "The current UPS load expressed in percent\nof rated capacity.",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_agent_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "agent_host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "snmp.UPS",
     "select": [
      [
       { "params": [ "upsAdvOutputLoad" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Battery Capacity",
   "type": "bargauge",
   "description": "The remaining battery capacity expressed in\npercent of full capacity.",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_agent_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "agent_host" ], "type": "tag" }
     ],
     "measurement": "snmp.UPS",
     "select": [
      [
       { "params": [ "upsAdvBatteryCapacity" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Time On Battery",
   "type": "stat",
   "description": "The elapsed time since the UPS has switched to battery power in seconds.",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "snmp.UPS",
     "select": [
      [
       { "params": [ "upsBasicBatteryTimeOnBattery" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Battery Transfer Reason",
   "type": "stat",
   "description": "The reason for the occurrence of the last transfer to UPS battery power.",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "snmp.UPS",
     "select": [
      [
       { "params": [ "upsAdvInputLineFailCause" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Battery Status",
   "type": "stat",
   "description": "Indicates whether the UPS batteries need replacing.",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "snmp.UPS",
     "select": [
      [
       { "params": [ "upsAdvBatteryReplaceIndicator" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Battery Uptime Remaining",
   "type": "stat",
   "description": "The UPS battery run time remaining before battery exhaustion.",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "snmp.UPS",
     "select": [
      [
       { "params": [ "upsAdvBatteryRunTimeRemaining" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Status",
   "type": "stat",
   "description": "The current state of the UPS. If the UPS is unable to determine the state of the UPS this variable is set to unknown.",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "snmp.UPS",
     "select": [
      [
       { "params": [ "upsBasicOutputStatus" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Self-test Result",
   "type": "stat",
   "description": "The results of the last UPS diagnostics test performed. ",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "snmp.UPS",
     "select": [
      [
       { "params": [ "upsAdvTestDiagnosticsResults" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Self-test Schedule",
   "type": "stat",
   "description": "The UPS system's automatic battery test schedule. ",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "snmp.UPS",
     "select": [
      [
       { "params": [ "upsAdvTestDiagnosticSchedule" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Battery Capacity",
   "type": "graph",
   "description": "The remaining battery capacity expressed in\npercent of full capacity.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "percent", "label": "Percent" }
   ],
   "targets": [
    {
     "alias": "$tag_agent_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "agent_host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "snmp.UPS",
     "select": [
      [
       { "params": [ "upsAdvBatteryCapacity" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Frequency ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "hertz", "label": "Hertz" }
   ],
   "targets": [
    {
     "alias": "$tag_agent_host (input)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "agent_host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "snmp.UPS",
     "select": [
      [
       { "params": [ "upsAdvInputFrequency" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "$tag_agent_host (output)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "agent_host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "snmp.UPS",
     "select": [
      [
       { "params": [ "upsAdvOutputFrequency" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "UPS Load",
   "type": "graph",
   "description": "The current UPS load expressed in percent\nof rated capacity.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "percent", "label": "Percent" }
   ],
   "targets": [
    {
     "alias": "$tag_agent_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "agent_host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "snmp.UPS",
     "select": [
      [
       { "params": [ "upsAdvOutputLoad" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Power Usage",
   "type": "graph",
   "description": "The total output active power of the UPS system in W. The total active power is the sum of phase 1, phase 2 and phase 3 power. ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_agent_host (watt)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "agent_host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "snmp.UPS",
     "select": [
      [
       { "params": [ "upsAdvOutputActivePower" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "$tag_agent_host (volt-ampere)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "agent_host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "snmp.UPS",
     "select": [
      [
       { "params": [ "upsAdvOutputApparentPower" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Line Voltage",
   "type": "graph",
   "description": "The current utility line voltage in VAC.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "volt", "label": "Volt" }
   ],
   "targets": [
    {
     "alias": "$tag_agent_host (input)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "agent_host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "snmp.UPS",
     "select": [
      [
       { "params": [ "upsAdvInputLineVoltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "- 1" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "$tag_agent_host (output)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "agent_host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "snmp.UPS",
     "select": [
      [
       { "params": [ "upsAdvOutputVoltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "- 1" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Power Usage",
   "type": "graph",
   "description": "The total output active power of the UPS system in W. The total active power is the sum of phase 1, phase 2 and phase 3 power. ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "kwatth", "label": "Kilowatt-hour" }
   ],
   "targets": [
    {
     "alias": "$tag_agent_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "agent_host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "snmp.UPS",
     "select": [
      [
       { "params": [ "upsAdvOutputActivePower" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Battery Bus Voltage",
   "type": "graph",
   "description": "The actual battery bus voltage in Volts.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "volt", "label": "Volt" }
   ],
   "targets": [
    {
     "alias": "$tag_agent_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "agent_host" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "snmp.UPS",
     "select": [
      [
       { "params": [ "upsAdvBatteryActualVoltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "graph",
   "description": "The current internal UPS temperature expressed in\nCelsius.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "fahrenheit", "label": "Degree" }
   ],
   "targets": [
    {
     "alias": "$tag_agent_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "agent_host" ], "type": "tag" },
      { "params": [ "agent_host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "snmp.UPS",
     "select": [
      [
       { "params": [ "upsAdvBatteryTemperature" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "* 9/5 + 32" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Ampere",
   "type": "graph",
   "description": "The current in ampres drawn by the load on the UPS.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "amp", "label": "Ampere" }
   ],
   "targets": [
    {
     "alias": "$tag_agent_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "agent_host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "snmp.UPS",
     "select": [
      [
       { "params": [ "upsHighPrecOutputCurrent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  }
 ]
}