{
 "title": "Dashboard Copy",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "influxdb" },
   {
    "name": "host",
    "query": "SHOW TAG VALUES FROM \"uptime\" WITH KEY = \"host\""
   },
   {
    "name": "temp_cpus",
    "query": "SHOW TAG VALUES FROM \"temperature\" WITH KEY = \"resource\" WHERE \"host\" =~ /^$host$/ "
   },
   {
    "name": "temp_disks",
    "query": "SHOW TAG VALUES FROM \"temperature\" WITH KEY = \"resource\" WHERE \"host\" =~ /^$host$/ "
   },
   {
    "name": "pools",
    "query": "SHOW TAG VALUES FROM \"df_complex-free\" WITH KEY = \"resource\" WHERE \"host\" =~ /^$host$/ "
   },
   {
    "name": "folders",
    "query": "SHOW TAG VALUES FROM \"df_complex-free\" WITH KEY = \"resource\" WHERE (\"host\" =~ /^$host$/ AND \"resource\" =~ /^${pools}-.*$/)"
   }
  ]
 },
 "panels": [
  {
   "title": "Panel Title",
   "type": "text",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "options": {
    "content": "<p style=\"text-align:center; vertical-align: middle;\">\n<img src=\"https://raw.githubusercontent.com/Condoamanti/grafana/master/dashboard/truenas/Logo.PNG\" style=\"background-color:white\" height=\"125\" alt=\"TRUENAS\"/>\n</p>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "uptime",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 2, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "interrupt",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "gauge-interrupt",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "resource", "operator": "=", "value": "aggregation-cpu-average" }
     ]
    },
    {
     "alias": "nice",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "gauge-nice",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "resource", "operator": "=", "value": "aggregation-cpu-average" }
     ]
    },
    {
     "alias": "system",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "gauge-system",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "resource", "operator": "=", "value": "aggregation-cpu-average" }
     ]
    },
    {
     "alias": "user",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "gauge-user",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "resource", "operator": "=", "value": "aggregation-cpu-average" }
     ]
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes", "label": "memory" }
   ],
   "targets": [
    {
     "alias": "active",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "memory-active",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "resource", "operator": "=", "value": "memory" }
     ]
    },
    {
     "alias": "cache",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "memory-cache",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "resource", "operator": "=", "value": "memory" }
     ]
    },
    {
     "alias": "inactive",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "memory-inactive",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "resource", "operator": "=", "value": "memory" }
     ]
    },
    {
     "alias": "laundry",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "memory-laundry",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "resource", "operator": "=", "value": "memory" }
     ]
    },
    {
     "alias": "wired",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "memory-wired",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "free",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "memory-free",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "interrupt",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "gauge-interrupt",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "resource", "operator": "=", "value": "aggregation-cpu-average" }
     ]
    },
    {
     "alias": "nice",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "gauge-nice",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "resource", "operator": "=", "value": "aggregation-cpu-average" }
     ]
    },
    {
     "alias": "system",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "gauge-system",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "resource", "operator": "=", "value": "aggregation-cpu-average" }
     ]
    },
    {
     "alias": "user",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "gauge-user",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "resource", "operator": "=", "value": "aggregation-cpu-average" }
     ]
    }
   ]
  },
  {
   "title": "Disk Temperature",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "celsius", "label": "celcius" }
   ],
   "targets": [
    {
     "alias": "$tag_resource",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "resource" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "temperature",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "resource", "operator": "=~", "value": "/^$temp_disks$/" }
     ]
    }
   ]
  },
  {
   "title": "Pool Capacity - $pools",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "$tag_resource-free",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "resource" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "df_complex-free",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "resource", "operator": "=~", "value": "/^$pools$/" }
     ]
    },
    {
     "alias": "$tag_resource-used",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "resource" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "df_complex-used",
     "query": "SELECT mean(\"value\") FROM \"df_complex-used\" WHERE (\"resource\" =~ /^$pools$/) AND $timeFilter GROUP BY time($__interval), \"resource\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "resource", "operator": "=~", "value": "/^$folders$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU Temperature",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "celsius", "label": "celcius" }
   ],
   "targets": [
    {
     "alias": "$tag_resource",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "resource" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "temperature",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "/ 10 - 273.15" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "resource", "operator": "=~", "value": "/^$temp_cpus$/" }
     ]
    }
   ]
  }
 ]
}